services:
  - type: web
    name: ingredients-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: API_KEY
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: ingredients-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ingredients-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ingredients-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ingredients-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ingredients-db
          property: password

databases:
  - name: ingredients-db
    databaseName: ingredients_db
    user: postgres